/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.vaadin.sass.internal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int S = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int CDO = 8;
  /** RegularExpression Id. */
  int CDC = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int DASHMATCH = 11;
  /** RegularExpression Id. */
  int PREFIXMATCH = 12;
  /** RegularExpression Id. */
  int SUFFIXMATCH = 13;
  /** RegularExpression Id. */
  int SUBSTRINGMATCH = 14;
  /** RegularExpression Id. */
  int INCLUDES = 15;
  /** RegularExpression Id. */
  int EQ = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int SEMICOLON = 20;
  /** RegularExpression Id. */
  int PRECEDES = 21;
  /** RegularExpression Id. */
  int SIBLING = 22;
  /** RegularExpression Id. */
  int SUCCEEDS = 23;
  /** RegularExpression Id. */
  int DIV = 24;
  /** RegularExpression Id. */
  int LBRACKET = 25;
  /** RegularExpression Id. */
  int RBRACKET = 26;
  /** RegularExpression Id. */
  int ANY = 27;
  /** RegularExpression Id. */
  int MOD = 28;
  /** RegularExpression Id. */
  int PARENT = 29;
  /** RegularExpression Id. */
  int DOT = 30;
  /** RegularExpression Id. */
  int ELLIPSIS = 31;
  /** RegularExpression Id. */
  int LPARAN = 32;
  /** RegularExpression Id. */
  int RPARAN = 33;
  /** RegularExpression Id. */
  int COMPARE = 34;
  /** RegularExpression Id. */
  int NOT_EQ = 35;
  /** RegularExpression Id. */
  int GTE = 36;
  /** RegularExpression Id. */
  int LTE = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int COLON = 41;
  /** RegularExpression Id. */
  int START_INTERPOLATION = 42;
  /** RegularExpression Id. */
  int NONASCII = 43;
  /** RegularExpression Id. */
  int H = 44;
  /** RegularExpression Id. */
  int UNICODE = 45;
  /** RegularExpression Id. */
  int ESCAPE = 46;
  /** RegularExpression Id. */
  int NMSTART = 47;
  /** RegularExpression Id. */
  int NMCHAR = 48;
  /** RegularExpression Id. */
  int STRINGCHAR = 49;
  /** RegularExpression Id. */
  int D = 50;
  /** RegularExpression Id. */
  int NAME = 51;
  /** RegularExpression Id. */
  int TO = 52;
  /** RegularExpression Id. */
  int THROUGH = 53;
  /** RegularExpression Id. */
  int EACH_IN = 54;
  /** RegularExpression Id. */
  int FROM = 55;
  /** RegularExpression Id. */
  int MIXIN_SYM = 56;
  /** RegularExpression Id. */
  int INCLUDE_SYM = 57;
  /** RegularExpression Id. */
  int FUNCTION_SYM = 58;
  /** RegularExpression Id. */
  int RETURN_SYM = 59;
  /** RegularExpression Id. */
  int DEBUG_SYM = 60;
  /** RegularExpression Id. */
  int WARN_SYM = 61;
  /** RegularExpression Id. */
  int FOR_SYM = 62;
  /** RegularExpression Id. */
  int EACH_SYM = 63;
  /** RegularExpression Id. */
  int WHILE_SYM = 64;
  /** RegularExpression Id. */
  int IF_SYM = 65;
  /** RegularExpression Id. */
  int ELSE_SYM = 66;
  /** RegularExpression Id. */
  int ELSEIF_SYM = 67;
  /** RegularExpression Id. */
  int EXTEND_SYM = 68;
  /** RegularExpression Id. */
  int MOZ_DOCUMENT_SYM = 69;
  /** RegularExpression Id. */
  int SUPPORTS_SYM = 70;
  /** RegularExpression Id. */
  int CONTENT_SYM = 71;
  /** RegularExpression Id. */
  int IF = 72;
  /** RegularExpression Id. */
  int LBRACE = 73;
  /** RegularExpression Id. */
  int MICROSOFT_RULE = 74;
  /** RegularExpression Id. */
  int GUARDED_SYM = 75;
  /** RegularExpression Id. */
  int STRING = 76;
  /** RegularExpression Id. */
  int NUMBER = 77;
  /** RegularExpression Id. */
  int _URL = 78;
  /** RegularExpression Id. */
  int _URL_FIRST = 79;
  /** RegularExpression Id. */
  int _URL_STRING = 80;
  /** RegularExpression Id. */
  int URL = 81;
  /** RegularExpression Id. */
  int IDENT = 82;
  /** RegularExpression Id. */
  int VARIABLE = 83;
  /** RegularExpression Id. */
  int PERCENTAGE = 84;
  /** RegularExpression Id. */
  int PT = 85;
  /** RegularExpression Id. */
  int MM = 86;
  /** RegularExpression Id. */
  int CM = 87;
  /** RegularExpression Id. */
  int PC = 88;
  /** RegularExpression Id. */
  int IN = 89;
  /** RegularExpression Id. */
  int PX = 90;
  /** RegularExpression Id. */
  int EMS = 91;
  /** RegularExpression Id. */
  int LEM = 92;
  /** RegularExpression Id. */
  int REM = 93;
  /** RegularExpression Id. */
  int EXS = 94;
  /** RegularExpression Id. */
  int DEG = 95;
  /** RegularExpression Id. */
  int RAD = 96;
  /** RegularExpression Id. */
  int GRAD = 97;
  /** RegularExpression Id. */
  int MS = 98;
  /** RegularExpression Id. */
  int SECOND = 99;
  /** RegularExpression Id. */
  int HZ = 100;
  /** RegularExpression Id. */
  int KHZ = 101;
  /** RegularExpression Id. */
  int DIMEN = 102;
  /** RegularExpression Id. */
  int HASH = 103;
  /** RegularExpression Id. */
  int IMPORT_SYM = 104;
  /** RegularExpression Id. */
  int MEDIA_SYM = 105;
  /** RegularExpression Id. */
  int CHARSET_SYM = 106;
  /** RegularExpression Id. */
  int PAGE_SYM = 107;
  /** RegularExpression Id. */
  int FONT_FACE_SYM = 108;
  /** RegularExpression Id. */
  int KEY_FRAME_SYM = 109;
  /** RegularExpression Id. */
  int ATKEYWORD = 110;
  /** RegularExpression Id. */
  int IMPORTANT_SYM = 111;
  /** RegularExpression Id. */
  int RANGE0 = 112;
  /** RegularExpression Id. */
  int RANGE1 = 113;
  /** RegularExpression Id. */
  int RANGE2 = 114;
  /** RegularExpression Id. */
  int RANGE3 = 115;
  /** RegularExpression Id. */
  int RANGE4 = 116;
  /** RegularExpression Id. */
  int RANGE5 = 117;
  /** RegularExpression Id. */
  int RANGE6 = 118;
  /** RegularExpression Id. */
  int RANGE = 119;
  /** RegularExpression Id. */
  int UNI = 120;
  /** RegularExpression Id. */
  int UNICODERANGE = 121;
  /** RegularExpression Id. */
  int NOT_FUNCTION = 122;
  /** RegularExpression Id. */
  int FUNCTION = 123;
  /** RegularExpression Id. */
  int FUNCTION_WITH_WS = 124;
  /** RegularExpression Id. */
  int UNKNOWN = 125;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ELSE_STATE = 1;
  /** Lexical state. */
  int PARSE_FUNCTIONNAME_WHITESPACE_ALLOWED_STATE = 2;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 3>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"<!--\"",
    "\"-->\"",
    "\"}\"",
    "\"|=\"",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"~=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\";\"",
    "\">\"",
    "\"~\"",
    "\"<\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\"%\"",
    "\"&\"",
    "\".\"",
    "\"...\"",
    "\"(\"",
    "\")\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\":\"",
    "\"#{\"",
    "<NONASCII>",
    "<H>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRINGCHAR>",
    "<D>",
    "<NAME>",
    "\"to\"",
    "\"through\"",
    "\"in\"",
    "\"from\"",
    "\"@mixin\"",
    "\"@include\"",
    "\"@function\"",
    "\"@return\"",
    "\"@debug\"",
    "\"@warn\"",
    "\"@for\"",
    "\"@each\"",
    "\"@while\"",
    "\"@if\"",
    "\"@else\"",
    "\"@elseif\"",
    "\"@extend\"",
    "\"@-moz-document\"",
    "\"@supports\"",
    "\"@content\"",
    "\"if\"",
    "\"{\"",
    "<MICROSOFT_RULE>",
    "<GUARDED_SYM>",
    "<STRING>",
    "<NUMBER>",
    "<_URL>",
    "<_URL_FIRST>",
    "<_URL_STRING>",
    "<URL>",
    "<IDENT>",
    "<VARIABLE>",
    "<PERCENTAGE>",
    "<PT>",
    "<MM>",
    "<CM>",
    "<PC>",
    "<IN>",
    "<PX>",
    "<EMS>",
    "<LEM>",
    "<REM>",
    "<EXS>",
    "<DEG>",
    "<RAD>",
    "<GRAD>",
    "<MS>",
    "<SECOND>",
    "<HZ>",
    "<KHZ>",
    "<DIMEN>",
    "<HASH>",
    "\"@import\"",
    "\"@media\"",
    "\"@charset\"",
    "\"@page\"",
    "\"@font-face\"",
    "<KEY_FRAME_SYM>",
    "<ATKEYWORD>",
    "<IMPORTANT_SYM>",
    "<RANGE0>",
    "<RANGE1>",
    "<RANGE2>",
    "<RANGE3>",
    "<RANGE4>",
    "<RANGE5>",
    "<RANGE6>",
    "<RANGE>",
    "<UNI>",
    "<UNICODERANGE>",
    "<NOT_FUNCTION>",
    "<FUNCTION>",
    "<FUNCTION_WITH_WS>",
    "<UNKNOWN>",
    "\"!optional\"",
  };

}
